#!/bin/sh

set -e

. "$(dirname $0)/config.sh"

for ARCH in $ARCHS
do
	VBOX="devstructure-ubuntu-$VERSION-$DISTRO-$ARCH"

	# Start the virtual machine.  Spin slowly until SSH is usable.
	VBoxManage startvm "$VBOX" --type gui
	#VBoxHeadless --startvm "$VBOX" --vrdp config
	until eval "$SSH exit"
	do
		sleep 1
	done

	# Install Ruby, RubyGems, and Chef as Vagrant requires.
	eval "$SSH \"
		set -e
		sudo apt-get -y install build-essential libopenssl-ruby ruby ruby-dev
		wget http://production.cf.rubygems.org/rubygems/rubygems-1.3.7.tgz
		tar xzf rubygems-1.3.7.tgz
		cd rubygems-1.3.7
		sudo ruby setup.rb --no-format-executable
		cd ..
		rm -rf rubygems-1.3.7 rubygems-1.3.7.tgz
		sudo gem install chef --no-rdoc --no-ri
	\""

	# Power off the virtual machine.
	VBoxManage controlvm "$VBOX" poweroff

	# Now build the Vagrant box file.
	BOX="devstructure$([ "$ARCH" = "i386" ] && echo 32 || echo 64)"
	vagrant package --base "$BOX"
	mv "package.box" "$BOX.box"

done
