#!/bin/sh

set -e

. "$(dirname $0)/config.sh"

ORIG="ubuntu-$VERSION-$DISTRO-$ARCH.iso"
COPY="ubuntu-$VERSION-$DISTRO-$ARCH"
ISO="$NICKNAME-ubuntu-$VERSION-$DISTRO-$ARCH.iso"

case $(uname) in
    'Linux')
        PLATFORM='linux' ;;
    'Darwin')
        PLATFORM='osx' ;;
    *)
        echo "Unsupported platform: $(uname)"
        exit 1 ;;
esac

# Download the original ISO if it isn't present already.
[ -f "$ORIG" ] || curl -L -o "$ORIG" \
	-d distro="$DISTRO" \
	-d release="$RELEASE" \
	-d bits="$([ "$ARCH" = "i386" ] && echo 32 || echo 64)" \
	"http://www.ubuntu.com/start-download"

# Make a writable copy of the original ISO.
case "$PLATFORM" in
    'linux')
        mkdir -p mount
        sudo mount -o loop "$ORIG" mount ;;
    'osx')
        hdiutil attach -mountpoint "mount" "$ORIG" ;;
esac

rsync -a "mount/" "$COPY"

case "$PLATFORM" in
    'linux')
        sudo umount mount ;;
    'osx')
        hdiutil detach "mount" ;;
esac

chmod -R +w "$COPY"

# Customize the writable copy.
cp "isolinux.cfg" "$COPY/isolinux/"
m4 \
	-D __HOST__="$HOST" \
	-D __DOMAIN__="$DOMAIN" \
	-D __KERNEL__="linux-$([ "$ARCH" = "i386" ] \
		&& echo generic-pae \
		|| echo server
	)" \
	-D __ROOT_PASSWORD__="$ROOT_PASSWORD" \
	-D __USERNAME__="$USERNAME" \
	-D __PASSWORD__="$PASSWORD" \
	"unattended.seed.m4" >"$COPY/preseed/unattended.seed"
cp "$PUBLIC_KEY" "sudoers" "$COPY/"
m4 \
	-D __USERNAME__="$USERNAME" \
	-D __PUBLIC_KEY__="$PUBLIC_KEY" \
	"late_command.sh.m4" >"$COPY/late_command.sh"

# Build a custom ISO.
mkisofs -r -V "Ubuntu $VERSION for Vagrant" \
	-cache-inodes -J -l -no-emul-boot \
	-b isolinux/isolinux.bin \
	-c isolinux/boot.cat \
	-boot-load-size 4 -boot-info-table \
	-o "$ISO" "$COPY"
